### ISSUE TITLE
全新安装的deepin 15.10无法使用

### ISSUE THREAD

**Issue by angelfind** [sonichy/dde-dock-datetime#1]
如果在deepin15.10以前的版本就安装了此插件, 然后在升级到15.10的话没问题. 但是如果是全新安装的deepin 15.10提示不能使用该插件, 应该是说不兼容的意思, 希望可以15.10下重新编译更新下插件. 希望可以勾选, 是否显示星期. 时间显示在第一行, 日期显示在第二行. 或者能让用户自定义格式化 HH:mm\r\nyyyy-MM-dd 就完美了.

**Comment by sonichy** [comment]
格式自定义，这个主意不错啊！emmm，需要给时间一个像天气那样的设置菜单。
从下个版本开始，将发布到release频道，并标注dde-dock版本。
请帮顶官方设计dde-dock插件版本检查功能：https://github.com/linuxdeepin/developer-center/issues/1193

**Comment by sonichy** [comment]
@angelfind 
![](https://raw.githubusercontent.com/sonichy/dde-dock-datetime/V1.3/format.jpg)

**Comment by angelfind** [comment]
@sonichy 非常感谢这么快就做出了更新。我尝试下载新版安装，但是貌似下载的zip文件解压后，目录里面没有install.sh文件造成无法安装。

**Comment by sonichy** [comment]
@angelfind 在Release频道里。

**Comment by angelfind** [comment]
@sonichy 我再次尝试安装插件， 不过很可惜没能安装上。我的系统是全新安装的deepin 15.10 (非老版本deepin升级上来的), 我在老版本中就有使用过您的插件， 能安装成功。然后系统会自动升级到15.10，这种从老版本升级到15.10的没问题能正常使用。前两天我手贱下载了一个最新版本deepin-15.10的全新安装文件安装系统， 在这全新安装的15.10中就是无法使用您的系统.  安装文件一执行完killall dde-dock, dock就会重启， 接着就提示： 插件libdatetime1.so和系统版本不兼容。不知道什么原因， 实在不好意思在麻烦你了。非常感谢。

**Comment by sonichy** [comment]
用户不能用我的软件，着急的是我好吧。
送官 @BLumia

**Comment by angelfind** [comment]
@sonichy 这个问题估计是要在全新安装的deepin 15.10系统里面重新配置生产环境才能调试出什么原因来。

**Comment by sonichy** [comment]
可能需要重新编译，等待官方解决。

**Comment by BLumia** [comment]
> 可能需要重新编译，等待官方解决。

我不是负责商店的..

不过还是确认一下，是官方商店提供的你的这个插件无法使用吗？

**Comment by angelfind** [comment]
不是, 就是从 github 上你说的release频道下载的V1.3插件不能用在deepin-15.10上.

**Comment by BLumia** [comment]
那这就是分发问题了，Deepin 肯定不会去解决这种问题。酱油应该考虑放个 deepin stable 用的 binary 给用户用。

-----------

~~ps. 酱油你要折腾不好分发我就要 [抢生意](https://github.com/BLumia/dde-dock-pineappledatetime) 了啊~~
pps. 如果酱油不清楚为啥需要重新编译的话——你链接的 qt 库版本是不一样的啊，不可能做到这种程度的一份 binary 两个版本共用的。

**Comment by sonichy** [comment]
@BLumia 你的意思，我的系统是 unstable ？

**Comment by BLumia** [comment]
> @BLumia 你的意思，我的系统是 unstable ？

你不说的话我哪知道你是 stable 还是 unstable ...

不过显然你只提供了一个版本，要么是 stable 要么是 unstable 版，显然总有一个是不能用的（

**Comment by sonichy** [comment]
怎么查 stable 还是 unstable ?
cat /etc/apt/sources.list
lion相当于stable，panda相当于unstable。
想切stable，将unstable或者panda改成stable或者lion就可以了。
但是如果在unstable下装了软件，切回stable有可能会破坏依赖关系，因为unstable的软件比较新。

**Comment by angelfind** [comment]
我的是lion stable版本系统。

**Comment by BLumia** [comment]
> 怎么查 stable 还是 unstable ?
> cat /etc/apt/sources.list
> lion相当于stable，panda相当于unstable。
> 想切stable，将unstable或者panda改成stable或者lion就可以了。
> 但是如果在unstable下装了软件，切回stable有可能会破坏依赖关系，因为unstable的软件比较新。

## **！警告：不建议直接通过修改仓库地址/名称来切换 stable 和 unstable，可能产生严重的依赖问题！**

直接改仓库地址之后你并没有真正切换 stable 和 unstable ，事实上你还需要 dist-upgrade 跑一次，这时候你的很多库都可能会升级（或是降级，如果是从 unstable 到 stable 的话，这其中包括 Qt）。由于此过程涉及到整个系统中大部分包的升级降级，所以可能存在大量的软件包依赖问题，如果你不清楚自己在做什么，请不要这么做！

**Comment by sonichy** [comment]
所以，lion（stable）分支请有能力的同学编译push上来！

**Comment by angelfind** [comment]
实在无法忍受托盘菜单里面一眼看不到日期, 在回收站里找到了deepin15.9的安装文件, 重新刻盘安装了. 就能安装上这个插件了.

**Comment by sonichy** [comment]
我服你了，为了一个插件重装系统，为什么你不自己编译呢，分分钟搞定，这么多大神可以咨询。

**Comment by angelfind** [comment]
没办法(龇牙表情) ，为了今后一直用这个系统，已经抛弃了很多在win下要用的软件，有的实在没办法抛弃的就只能自己封装一下在deepin中用，尝试编译这个插件，可能是环境没配置好编译出来的插件还是不能用在15.10中，迫不得已，实在无法忍受看不到日期。只好放弃配置的差不多的系统，重新来过一次。现在就完美解决了。方法：安装deepin 15.09后, 把插件插上，然后在把系统升级到15.10，进入15.10系统后欢喜的看到插件还是正常运行了心里就长舒了一口气，接着配置工作环境，要不然对于我这样的强迫症来说估计要放弃系统了。

**Comment by BLumia** [comment]
编译没那么麻烦吧，酱油可能需要写个简要文档写怎么构建？写完了还可以扔 bbs 水一篇，一举两得（

**Comment by sonichy** [comment]
@BLumia 注意这句话：编译出来的插件还是不能用在15.10，会不会是API版太高了？

**Comment by BLumia** [comment]
> @BLumia 注意这句话：编译出来的插件还是不能用在15.10，会不会是API版太高了？
> >**可能是环境没配置好**编译出来的插件还是不能用在15.10中

在没有更多详细信息的情况下我无法判断原因..至少应该提供构建环境和步骤以便描述问题的人之外的人可以复现问题对吧？

酱油可以考虑搞一搞这个需求 https://github.com/linuxdeepin/developer-center/issues/1193 然后来个 PR ？
