### ISSUE TITLE
V20 efficient plugin not visible full

### ISSUE THREAD

**Issue by 8008698** [sonichy/dde-dock-datetime#3]
very small area used by this plugin not visible date and time on dock efficient mode dde v30 1003

**Comment by sonichy** [comment]
Please install 1003 special version to hack dde-dock bug.

**Comment by aksharlabs** [comment]
same here with v20.1( 1010) using latest master branch

![Screen Capture_select-area_20210101204107](https://user-images.githubusercontent.com/74598801/103438036-b2389480-4c71-11eb-8e5e-e1211e62cebe.png)

**Comment by sonichy** [comment]
Check if you installed v1.6.1003 successful !
After installed, check the file time of /usr/lib/dde-dock/plugins/libdatetime1.so

**Comment by aksharlabs** [comment]
> Check if you installed v1.6.1003 successful !
> After installed, check the file time of /usr/lib/dde-dock/plugins/libdatetime1.so

i have installed that version but plugin size is not showing full. there is not problem in fashion mode
dde dock version is as follows
` sudo apt policy dde-dock
dde-dock:
  Installed: 5.3.0.54-1
  Candidate: 5.3.0.54-1
  Version table:
 *** 5.3.0.54-1 500
        500 https://community-packages.deepin.com/deepin apricot/main amd64 Packages
        100 /usr/lib/dpkg-db/status
`

**Comment by 8008698** [comment]
Problem is with newer version of dde-dock. Older version dock has no problem with plugin. May be on new dock there is different code fore resize plugin area.

**Comment by sonichy** [comment]
I am using the newest version, and no one else report your problem.
https://www.deepin.org/zh/2020/12/28/deepin-20-1-details-make-perfection/

**Comment by aksharlabs** [comment]
oh pre built plugin works perfect but when i build from source that have problem with size.

![Screen Capture_select-area_20210103220229](https://user-images.githubusercontent.com/74598801/103479230-99fe7c00-4e0f-11eb-99cc-526885d44798.png)

**Comment by sonichy** [comment]
Because source have not change to hack code.
https://github.com/sonichy/dde-dock-datetime/blob/master/datetimeplugin.cpp#L56
```
//return "datetime1";
return "datetime";
```

**Comment by aksharlabs** [comment]
> Because source have not change to hack code.
> https://github.com/sonichy/dde-dock-datetime/blob/master/datetimeplugin.cpp#L56
> 
> ```
> //return "datetime1";
> return "datetime";
> ```

Doing this way it is not possible to disable or enable  plugin default datetime and datetime1 independently.

**Comment by sonichy** [comment]
Yes, you already know.
