### ISSUE TITLE
请问还在维护吗

### ISSUE THREAD

**Issue by chenzhiwei** [sonichy/dde-dock-datetime#4]
感觉点击时间插件跳出如下窗口就挺好，再点击如下窗口跳出深度日历。

![image](https://user-images.githubusercontent.com/672668/115084846-06733600-9f3c-11eb-8a22-415c76c2a4d5.png)

**Comment by sonichy** [comment]
现在是这样的啊，跳转深度日历干啥？

**Comment by chenzhiwei** [comment]
因为系统默认插件就是跳转到深度日历啊

**Comment by sonichy** [comment]
我不喜欢默认的设计啊
