### ISSUE TITLE
您好，请问这个插件目前还维护吗？

### ISSUE THREAD

**Issue by liwl1991** [sonichy/dde-dock-datetime#5]
我正在使用这个插件，很好用，感谢！
但是有几个问题：
1. 右键菜单选项是英文，请问是设计如此吗？
2. 我使用qtcreator编译以后，放到路径下，右键无法使用，请问是我编译的问题吗

**Comment by sonichy** [comment]
1.我不会多语言，为了外国用户，干脆用英文。
2.电脑送走了，deepin20.5 开始没有编译测试了。

**Comment by liwl1991** [comment]
> 1.我不会多语言，为了外国用户，干脆用英文。 2.电脑送走了，deepin20.5 开始没有编译测试了。

好的，感谢您回复！
当前deepin最新版本20.6编译有问题，能够确认是dde-dock的问题。修改dde-dock的代码能够编译成功，但是插件设置部分没有了字体部分的设置，请问是否是我这边的问题？还是代码并非最新的呢？

**Comment by sonichy** [comment]
代码非最新
